<a href="https://colab.research.google.com/github/Dhruvit-Agrawal/PyTorch/blob/main/1_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
print(torch.__version__)

2.5.1+cu121


In [ ]:
if torch.cuda.is_available():
    print("cuda is available")
else:
    print("cuda is not available")

cuda is available


#Tensors

In [ ]:
#using empty function
x=torch.empty(5,3)
print(x)

tensor([[7.0678e+28, 4.8418e+30, 3.1365e-18],
        [3.0186e+32, 1.4605e-19, 1.0899e+27],
        [6.7404e+22, 1.5766e-19, 1.1434e+27],
        [2.9907e+21, 1.7036e+19, 1.8019e+31],
        [1.8062e+28, 1.5766e-19, 1.1434e+27]])


In [ ]:
#zeroes
x=torch.zeros(5,3)
print(x)

#ones
x=torch.ones(5,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
#random between 5,10
x=torch.randint(5,10,(5,3))
print(x)

tensor([[7, 7, 9],
        [7, 6, 8],
        [6, 6, 7],
        [7, 7, 9],
        [9, 8, 7]])


In [ ]:
#custom tensor
x=torch.tensor([[5.5,0,5],(2,3,3),[8,5,4]])
print(x)

tensor([[5.5000, 0.0000, 5.0000],
        [2.0000, 3.0000, 3.0000],
        [8.0000, 5.0000, 4.0000]])


In [ ]:
#linspace
x=torch.linspace(1,10,5)
print(x)

#identity
x=torch.eye(5)
print(x)

#full
x=torch.full((5,3),5)
print(x)

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [ ]:
#_like functions
x=torch.empty(5,3)
y=torch.zeros_like(x)
print(y)

y=torch.ones_like(x)
print(y)

y=torch.rand_like(x)
print(y)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.6501, 0.6407, 0.0159],
        [0.1986, 0.7220, 0.1050],
        [0.9047, 0.1259, 0.0296],
        [0.7299, 0.5885, 0.0275],
        [0.5182, 0.4328, 0.9609]])


In [ ]:
#data types
x=torch.empty(5,3,dtype=torch.float)
print(x)

x=torch.empty(5,3,dtype=torch.double)
print(x)

print(x.dtype)
print(f"running to() function")
x=x.to(torch.int)
print(x.dtype)

tensor([[0.0000e+00, 0.0000e+00, 1.6201e-33],
        [3.1435e-41, 2.1342e-35, 3.1435e-41],
        [2.6395e+03, 4.4755e-41, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
tensor([[6.7775e-310, 4.7603e-310, 2.3549e+251],
        [8.0334e-304, 2.2517e+289, 3.3939e-111],
        [3.1536e+161, 3.9991e+252, 1.0376e+243],
        [2.3529e+251, 6.0598e+233, 8.7642e+252],
        [1.0376e+243, 3.5902e+246, 9.0011e+223]], dtype=torch.float64)
torch.float64
running to() function
torch.int32


#Mathematical Functions

In [ ]:
##addition
x=torch.rand(5,3)
y=torch.rand(5,3)
z=x+y
print(z)

z=torch.add(x,y)
print(z)

tensor([[0.1793, 1.2940, 0.7964],
        [0.9308, 1.7505, 0.7961],
        [1.1895, 0.6781, 0.9057],
        [1.2225, 1.3448, 0.6962],
        [0.7624, 0.9863, 1.3405]])
tensor([[0.1793, 1.2940, 0.7964],
        [0.9308, 1.7505, 0.7961],
        [1.1895, 0.6781, 0.9057],
        [1.2225, 1.3448, 0.6962],
        [0.7624, 0.9863, 1.3405]])


In [ ]:
##multiplication
z=x*y
print(z)

z=torch.mul(x,y)
print(z)

tensor([[0.0077, 0.3997, 0.1020],
        [0.1161, 0.7644, 0.0791],
        [0.3092, 0.0950, 0.1126],
        [0.3730, 0.4399, 0.0825],
        [0.1187, 0.0155, 0.4468]])
tensor([[0.0077, 0.3997, 0.1020],
        [0.1161, 0.7644, 0.0791],
        [0.3092, 0.0950, 0.1126],
        [0.3730, 0.4399, 0.0825],
        [0.1187, 0.0155, 0.4468]])


In [ ]:
##division
z=x/y
print(z)

z=torch.div(x,y)
print(z)

##int division
z=x//y
print(z)

tensor([[ 0.6745,  1.5408,  3.9683],
        [ 0.1896,  0.9099,  5.8408],
        [ 0.4763,  0.4117,  0.1966],
        [ 0.9247,  1.3931,  3.5977],
        [ 0.4002, 60.9287,  1.1594]])
tensor([[ 0.6745,  1.5408,  3.9683],
        [ 0.1896,  0.9099,  5.8408],
        [ 0.4763,  0.4117,  0.1966],
        [ 0.9247,  1.3931,  3.5977],
        [ 0.4002, 60.9287,  1.1594]])


In [ ]:
##power
z=x**2
print(z)

z=torch.mul(x,x)
print(z)

tensor([[0.0052, 0.6158, 0.4046],
        [0.0220, 0.6955, 0.4620],
        [0.1473, 0.0391, 0.0221],
        [0.3450, 0.6128, 0.2968],
        [0.0475, 0.9417, 0.5180]])
tensor([[0.0052, 0.6158, 0.4046],
        [0.0220, 0.6955, 0.4620],
        [0.1473, 0.0391, 0.0221],
        [0.3450, 0.6128, 0.2968],
        [0.0475, 0.9417, 0.5180]])


In [ ]:
x=torch.tensor([[1,3],[1,1]])
print(x)
y=torch.tensor([[1,1],[1,1]])
print(y)

#matrix multiplication
z=torch.mm(x,y)
print(z)

tensor([[1, 3],
        [1, 1]])
tensor([[1, 1],
        [1, 1]])
tensor([[4, 4],
        [2, 2]])


In [ ]:
##### REDUCTION OPERATIONS #######

In [ ]:
##sum
x=torch.tensor([[1,3],[1,1]])
print(x)

z=torch.sum(x)
print(z)

#sum along col
z=torch.sum(x,dim=0)
print(z)

#sum along row
z=torch.sum(x,dim=1)
print(z)

tensor([[1, 3],
        [1, 1]])
tensor(6)
tensor([2, 4])
tensor([4, 2])


In [ ]:
#mean
z=torch.mean(x.float())    #works only on float dtype
print(z)

#median
z=torch.median(x)
print(z)

#min
z=torch.min(x)
print(z)

#max
z=torch.max(x)
print(z)


#argmax
z=torch.argmax(x)
print(z)

#argmin
z=torch.argmin(x)
print(z)

tensor(1.5000)
tensor(1)
tensor(1)
tensor(3)
tensor(1)
tensor(0)


In [ ]:
#std
z=torch.std(x.float())
print(z)

#var
z=torch.var(x.float())
print(z)



#Matrix Operations

In [ ]:
#mm
x=torch.tensor([[1,3],[1,1]])
print(x)
y=torch.tensor([[1,1],[1,1]])
print(y)

z=torch.mm(x,y)
print(z)

tensor([[1, 3],
        [1, 1]])
tensor([[1, 1],
        [1, 1]])
tensor([[4, 4],
        [2, 2]])


In [ ]:
#dot product
z=torch.dot(x[0],y[0])
print(z)

tensor(4)


In [ ]:
#transpose
z=torch.t(x)
print(z)

tensor([[1, 1],
        [3, 1]])


In [ ]:
#determinant
z=torch.linalg.det(x.float())
print(z)

#inverse
z=torch.linalg.inv(x.float())
print(z)

tensor(-2.0000)
tensor([[-0.5000,  1.5000],
        [ 0.5000, -0.5000]])


#Transforms

In [ ]:
#log
x=torch.tensor([[1,3],[1,1]])
print(x)

z=torch.log(x)
print(z)

tensor([[1, 3],
        [1, 1]])
tensor([[0.0000, 1.0986],
        [0.0000, 0.0000]])


In [ ]:
#exp
z=torch.exp(x.float())
print(z)

tensor([[ 2.7183, 20.0855],
        [ 2.7183,  2.7183]])


In [ ]:
#sqrt
z=torch.sqrt(x.float())
print(z)

tensor([[1.0000, 1.7321],
        [1.0000, 1.0000]])


In [ ]:
#sigmoid
z=torch.sigmoid(x.float())
print(z)

tensor([[0.7311, 0.9526],
        [0.7311, 0.7311]])


In [ ]:
#softmax
z=torch.softmax(x.float(),dim=1)  # 1--> row
print(z)                          # 0 --> col

tensor([[0.1192, 0.8808],
        [0.5000, 0.5000]])


In [ ]:
#relu
z=torch.relu(x.float())
print(z)

tensor([[1., 3.],
        [1., 1.]])


#Copying

In [ ]:
x=torch.tensor([[1,3],[1,1]])
print(x)

y=x

print(f"id of x:{id(x)}")
print(f"id of y:{id(y)}")

tensor([[1, 3],
        [1, 1]])
id of x:137173857198752
id of y:137173857198752


In [ ]:
y=x.clone()

print(f"id of x:{id(x)}")
print(f"id of y:{id(y)}")

id of x:137173857198752
id of y:137173825172912


#Operations on GPU

In [ ]:
#creating on gpu
if torch.cuda.is_available():
    device=torch.device("cuda")
else:
    device=torch.device("cpu")

x=torch.ones(5,3,device=device)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')


In [ ]:
#moving from cpu to gpu
y=torch.ones(5,3)
y=y.to(device)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')


#Reshaping

In [ ]:
#reshape
x=torch.rand(4,4)
print(x)

y=x.reshape(2,8)
print(y)

tensor([[0.0755, 0.0979, 0.2923, 0.1993],
        [0.6737, 0.5379, 0.5561, 0.2619],
        [0.4284, 0.4210, 0.7908, 0.3104],
        [0.8522, 0.1865, 0.2103, 0.4729]])
tensor([[0.0755, 0.0979, 0.2923, 0.1993, 0.6737, 0.5379, 0.5561, 0.2619],
        [0.4284, 0.4210, 0.7908, 0.3104, 0.8522, 0.1865, 0.2103, 0.4729]])


In [ ]:
#permute
z=x.permute(1,0)
print(z)

tensor([[0.0755, 0.6737, 0.4284, 0.8522],
        [0.0979, 0.5379, 0.4210, 0.1865],
        [0.2923, 0.5561, 0.7908, 0.2103],
        [0.1993, 0.2619, 0.3104, 0.4729]])


In [ ]:
#unsqueeze
z=x.unsqueeze(0)
print(z)
print(z.shape)

z=x.unsqueeze(1)
print(z)
print(z.shape)

tensor([[[0.0755, 0.0979, 0.2923, 0.1993],
         [0.6737, 0.5379, 0.5561, 0.2619],
         [0.4284, 0.4210, 0.7908, 0.3104],
         [0.8522, 0.1865, 0.2103, 0.4729]]])
torch.Size([1, 4, 4])
tensor([[[0.0755, 0.0979, 0.2923, 0.1993]],

        [[0.6737, 0.5379, 0.5561, 0.2619]],

        [[0.4284, 0.4210, 0.7908, 0.3104]],

        [[0.8522, 0.1865, 0.2103, 0.4729]]])
torch.Size([4, 1, 4])


In [ ]:
#squeeze
z=x.squeeze(0)
print(z)
print(z.shape)

z=x.squeeze(1)
print(z)
print(z.shape)

tensor([[0.0755, 0.0979, 0.2923, 0.1993],
        [0.6737, 0.5379, 0.5561, 0.2619],
        [0.4284, 0.4210, 0.7908, 0.3104],
        [0.8522, 0.1865, 0.2103, 0.4729]])
torch.Size([4, 4])
tensor([[0.0755, 0.0979, 0.2923, 0.1993],
        [0.6737, 0.5379, 0.5561, 0.2619],
        [0.4284, 0.4210, 0.7908, 0.3104],
        [0.8522, 0.1865, 0.2103, 0.4729]])
torch.Size([4, 4])
