<a href="https://colab.research.google.com/github/Dhruvit-Agrawal/PyTorch/blob/main/3_nn_ModuleBasic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn

In [ ]:
class MyModel(nn.Module):  #inhereting nn class

    def __init__(self, num_features):
        super().__init__()    #calling instructor of parent class using super() function
        self.linear1=nn.Linear(in_features=num_features,out_features=4)        #initalising  linear layer 1
        self.relu=nn.Sigmoid()                                                 #inialiting activation function

        self.linear2=nn.Linear(in_features=4, out_features=1)             #initalising linear layer 2
        self.sigmoid=nn.Sigmoid()                                         #initalising activation function

    def forward(self,x):
        x=self.linear1(x)
        x=self.relu(x)
        x=self.linear2(x)
        x=self.sigmoid(x)
        return (x)

In [ ]:
#dummy dataset
X=torch.rand(100,10)
y=torch.rand(100,1)

#model instance
model=MyModel(X.shape[1])

#forward pass
model(X)

tensor([[0.5059],
        [0.5049],
        [0.5042],
        [0.5110],
        [0.5063],
        [0.5041],
        [0.4989],
        [0.4992],
        [0.4976],
        [0.5100],
        [0.5073],
        [0.5015],
        [0.5104],
        [0.4974],
        [0.5007],
        [0.5015],
        [0.4990],
        [0.5157],
        [0.4926],
        [0.5109],
        [0.4952],
        [0.5012],
        [0.5041],
        [0.5081],
        [0.5054],
        [0.5097],
        [0.5085],
        [0.4999],
        [0.5088],
        [0.5124],
        [0.5063],
        [0.4960],
        [0.4996],
        [0.5100],
        [0.5025],
        [0.4999],
        [0.5053],
        [0.5036],
        [0.5095],
        [0.5069],
        [0.4988],
        [0.5059],
        [0.5066],
        [0.5033],
        [0.4986],
        [0.5114],
        [0.5052],
        [0.5064],
        [0.5050],
        [0.5175],
        [0.5114],
        [0.5036],
        [0.5046],
        [0.5112],
        [0.5105],
        [0

In [ ]:
#model weights
model.linear2.weight

Parameter containing:
tensor([[0.3846, 0.2517, 0.2093, 0.1287]], requires_grad=True)

In [ ]:
%%capture
!pip install torchinfo

In [ ]:
from torchinfo import summary

In [ ]:
#create summary
summary(model=model,input_size=(100,10))

Layer (type:depth-idx)                   Output Shape              Param #
MyModel                                  [100, 1]                  --
├─Linear: 1-1                            [100, 4]                  44
├─Sigmoid: 1-2                           [100, 4]                  --
├─Linear: 1-3                            [100, 1]                  5
├─Sigmoid: 1-4                           [100, 1]                  --
Total params: 49
Trainable params: 49
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.01

In [ ]:
class MyModel_using_sequential(nn.Module):  #inhereting nn class

    def __init__(self, num_features):
        super().__init__()    #calling instructor of parent class using super() function

        self.network=nn.Sequential(
            nn.Linear(in_features=num_features,out_features=4),        #initalising  linear layer 1
            nn.ReLU(),                                                 #inialiting activation function

            nn.Linear(in_features=4, out_features=1),             #initalising linear layer 2
            nn.Sigmoid()                                         #initalising activation function
        )

    def forward(self,x):

        out=self.network(x)
        return (x)

In [ ]:
#dummy dataset
X=torch.rand(100,10)
y=torch.rand(100,1)

#model instance
model=MyModel_using_sequential(X.shape[1])

#forward pass
model(X)

tensor([[3.9513e-01, 9.8117e-01, 3.1090e-01, 9.3044e-02, 4.6141e-01, 5.3395e-01,
         5.5490e-01, 7.2994e-01, 9.8205e-01, 8.0320e-01],
        [5.2389e-01, 4.7721e-01, 8.2757e-02, 6.6455e-01, 2.7221e-01, 1.1161e-01,
         3.6608e-01, 9.0869e-01, 7.4112e-01, 6.6132e-01],
        [9.0210e-01, 9.7398e-02, 7.8781e-01, 3.0611e-01, 7.3214e-01, 5.9623e-01,
         7.2097e-01, 5.0869e-01, 4.2393e-01, 6.0486e-01],
        [4.7026e-01, 1.0705e-02, 2.1239e-01, 9.7708e-01, 1.1335e-01, 7.5438e-01,
         3.8109e-01, 8.0884e-01, 7.6240e-01, 9.5505e-01],
        [4.5458e-01, 5.3628e-01, 1.1678e-01, 8.1626e-02, 5.4327e-01, 4.4730e-01,
         9.3326e-01, 6.5463e-03, 1.3670e-02, 4.7974e-01],
        [5.7455e-01, 8.0202e-01, 3.7749e-01, 4.9639e-02, 7.8087e-01, 2.9694e-01,
         5.8433e-01, 4.2435e-01, 8.4007e-01, 6.1799e-01],
        [5.7285e-01, 5.4558e-01, 8.4602e-02, 1.4157e-02, 5.2042e-01, 6.3907e-01,
         1.5156e-01, 2.9609e-01, 8.5163e-01, 3.4710e-01],
        [7.0559e-01, 1.1961

In [ ]:
summary(model=model,input_size=(100,10))

Layer (type:depth-idx)                   Output Shape              Param #
MyModel_using_sequential                 [100, 10]                 --
├─Sequential: 1-1                        [100, 1]                  --
│    └─Linear: 2-1                       [100, 4]                  44
│    └─ReLU: 2-2                         [100, 4]                  --
│    └─Linear: 2-3                       [100, 1]                  5
│    └─Sigmoid: 2-4                      [100, 1]                  --
Total params: 49
Trainable params: 49
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.01

In [ ]:
class MyModel_using_optim(nn.Module):  #inhereting nn class

    def __init__(self, num_features):
        super().__init__()    #calling instructor of parent class using super() function

        self.network=nn.Sequential(
            nn.Linear(in_features=num_features,out_features=4),        #initalising  linear layer 1
            nn.ReLU(),                                                 #inialiting activation function

            nn.Linear(in_features=4, out_features=1),             #initalising linear layer 2
            nn.Sigmoid()                                         #initalising activation function
        )

    def forward(self,x):

        y_pred=self.network(x)
        return (y_pred)

    def loss(self,y_pred,y):
        loss_fn=nn.BCELoss()
        loss=loss_fn(y_pred,y)
        return (loss)

    def train(self,loss,epoch=25,lr=0.01):

        #setting optimizer
        optimizer=torch.optim.SGD(params=self.network.parameters(),lr=lr)        # .parameters()--> stores all the trainable paramaets
        for i in range(epoch):

            #forward
            y_pred=self.network(X)

            #loss
            loss=self.loss(y_pred=y_pred,y=y)


            optimizer.zero_grad()                #clear gradient
            loss.backward()                      #backtrack
            optimizer.step()                     #update parameters

            #print loss
            print(f"epoch:{i+1},loss:{loss.item()}")



In [ ]:
#dummy dataset
X=torch.rand(100,10)
y=torch.rand(100,1)

#model instance
model=MyModel_using_optim(X.shape[1])



In [ ]:
#train
model.train(loss=loss)

epoch:1,loss:0.6933513879776001
epoch:2,loss:0.693347692489624
epoch:3,loss:0.6933439373970032
epoch:4,loss:0.6933403611183167
epoch:5,loss:0.6933367252349854
epoch:6,loss:0.6933330297470093
epoch:7,loss:0.6933294534683228
epoch:8,loss:0.6933258175849915
epoch:9,loss:0.6933221220970154
epoch:10,loss:0.6933184862136841
epoch:11,loss:0.6933149099349976
epoch:12,loss:0.6933112144470215
epoch:13,loss:0.6933075189590454
epoch:14,loss:0.6933040022850037
epoch:15,loss:0.6933003067970276
epoch:16,loss:0.6932967901229858
epoch:17,loss:0.6932930946350098
epoch:18,loss:0.6932895183563232
epoch:19,loss:0.6932858824729919
epoch:20,loss:0.6932823061943054
epoch:21,loss:0.6932786703109741
epoch:22,loss:0.6932750940322876
epoch:23,loss:0.6932713985443115
epoch:24,loss:0.6932678818702698
epoch:25,loss:0.6932643055915833


In [ ]:
summary(model=model,input_size=(100,10))

epoch:1,loss:0.693260669708252
epoch:2,loss:0.6932570934295654
epoch:3,loss:0.6932534575462341
epoch:4,loss:0.6932498812675476
epoch:5,loss:0.6932463049888611
epoch:6,loss:0.6932427287101746
epoch:7,loss:0.693239152431488
epoch:8,loss:0.6932355761528015
epoch:9,loss:0.6932319402694702
epoch:10,loss:0.6932284832000732
epoch:11,loss:0.6932248473167419
epoch:12,loss:0.6932212710380554
epoch:13,loss:0.6932177543640137
epoch:14,loss:0.6932141184806824
epoch:15,loss:0.6932106018066406
epoch:16,loss:0.6932070851325989
epoch:17,loss:0.6932035088539124
epoch:18,loss:0.6931999921798706
epoch:19,loss:0.6931964159011841
epoch:20,loss:0.6931928396224976
epoch:21,loss:0.6931893825531006
epoch:22,loss:0.6931857466697693
epoch:23,loss:0.6931822299957275
epoch:24,loss:0.6931787133216858
epoch:25,loss:0.6931751370429993
epoch:1,loss:0.6931716203689575
epoch:2,loss:0.693168044090271
epoch:3,loss:0.6931645274162292
epoch:4,loss:0.6931610703468323
epoch:5,loss:0.6931574940681458
epoch:6,loss:0.693153977394

Layer (type:depth-idx)                   Output Shape              Param #
├─Sequential: 1-1                        [100, 1]                  --
│    └─Linear: 2-1                       [100, 4]                  44
│    └─ReLU: 2-2                         [100, 4]                  --
│    └─Linear: 2-3                       [100, 1]                  5
│    └─Sigmoid: 2-4                      [100, 1]                  --
├─Sequential: 1-2                        [100, 1]                  (recursive)
│    └─Linear: 2-5                       [100, 4]                  (recursive)
│    └─ReLU: 2-6                         [100, 4]                  --
│    └─Linear: 2-7                       [100, 1]                  (recursive)
│    └─Sigmoid: 2-8                      [100, 1]                  --
├─Sequential: 1-3                        [100, 1]                  (recursive)
│    └─Linear: 2-9                       [100, 4]                  (recursive)
│    └─ReLU: 2-10                        