<a href="https://colab.research.google.com/github/Dhruvit-Agrawal/PyTorch/blob/main/4_Dataset_and_DataLoader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
import torch

#Data

In [ ]:
X,y = make_classification(n_samples=1000,n_features=10,n_informative=7,n_classes=2,random_state=42)

In [ ]:
X

array([[-1.14720209, -1.67085105,  1.37191918, ..., -0.55701547,
         4.35326455, -0.96387086],
       [-1.19138687, -2.28568567,  1.32071737, ...,  0.75880969,
        -1.42929981,  0.36995583],
       [-3.89725915, -3.4135366 , 10.1557105 , ..., -1.31135025,
        -1.19881651,  0.06205633],
       ...,
       [ 0.06839718, -0.14734047, -1.98719793, ...,  0.46309914,
         0.8479443 ,  0.92379027],
       [ 0.52196073,  2.11768567, -2.41530178, ...,  0.98272696,
         0.97138238,  1.62826282],
       [ 2.97468628, -1.47295068,  1.52823463, ..., -0.35961471,
        -1.31615397, -0.766366  ]])

In [ ]:
y

array([0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,

#numpy to tensor

In [ ]:
X_tensor=torch.from_numpy(X)
y_tensor=torch.from_numpy(y)

#Data loading

In [ ]:
from torch.utils.data import TensorDataset,DataLoader

In [ ]:
class custom_dataset(TensorDataset):

  def __init__(self,X,y):
    self.X=X
    self.y=y

  def __len__(self):                  #no input
    return self.X.shape[0]            #return size of features(size of data)

  def __getitem__(self,idx):          #indx input
    return self.X[idx],self.y[idx]    #return data at that index

In [ ]:
dataset=custom_dataset(X_tensor,y_tensor)

In [ ]:
len(dataset)

1000

In [ ]:
dataset[4]

(tensor([-2.4233, -0.4303,  0.3236, -0.7741,  0.1247, -0.4085, -2.5444, -1.7625,
         -0.5570,  2.9434], dtype=torch.float64),
 tensor(0))

In [ ]:
dataload=DataLoader(dataset,batch_size=4,shuffle=True)

In [ ]:
for batch_features,batch_labels in dataload:
  print(batch_features)
  print(batch_labels)
  print("-*-"*50)

tensor([[-3.2900,  0.1555,  0.4502, -1.9548,  0.3248, -1.3088, -1.8969,  0.7371,
         -0.9117,  4.1613],
        [-1.3833,  0.1356, -1.7650,  2.2943, -1.9257,  0.5669, -2.5322, -1.6366,
         -0.6750,  0.3913],
        [-0.7807,  2.8036, -4.2451,  0.7485, -1.6413,  0.5426, -0.7788, -1.7210,
         -0.3596,  0.5392],
        [ 0.5266,  0.5282,  0.6115,  1.1247,  1.1821,  0.6696, -1.7026,  0.2806,
          0.1121, -1.9699]], dtype=torch.float64)
tensor([0, 0, 0, 1])
-*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*-
tensor([[-0.8710,  0.1000, -0.4498, -2.5044,  1.6149,  0.5240, -0.6128,  0.9017,
          2.6009,  2.1179],
        [-1.4299, -1.4729, -0.1523, -4.0707,  1.5157,  2.1961, -0.0231, -0.3183,
          2.1640,  3.4057],
        [-2.6959,  1.3121, -0.0748, -5.0458,  1.2500,  1.9883,  2.3827, -0.0836,
         -2.8942,  2.4742],
        [-0.6144,  1.6408, -0.5025, -0.0699

#Applying on breast cancer dataset

In [ ]:
import torch
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
df.drop(columns=["id",'Unnamed: 32'],inplace=True)

##train test split

In [ ]:
#train test split
x=df.drop(columns=["diagnosis"])
y=df["diagnosis"]

x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2, random_state=42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(455, 30)
(114, 30)
(455,)
(114,)


##scaling

In [ ]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

##label encoding

In [ ]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

##numpy to tensor

In [ ]:
x_train_tensor=torch.from_numpy(x_train.astype(np.float32))
x_test_tensor=torch.from_numpy(x_test.astype(np.float32))
y_train_tensor=torch.from_numpy(y_train.astype(np.float32))
y_test_tensor=torch.from_numpy(y_test.astype(np.float32))

In [ ]:
print(x_train_tensor.shape)
print(x_test_tensor.shape)
print(y_train_tensor.shape)
print(y_test_tensor.shape)

torch.Size([455, 30])
torch.Size([114, 30])
torch.Size([455])
torch.Size([114])


##dataset and dataloader classes

In [ ]:
class customDataset(torch.utils.data.Dataset):
  def __init__(self,x,y):
    self.x=x
    self.y=y

  def __len__(self):
    return self.x.shape[0]

  def __getitem__(self,idx):
    return self.x[idx],self.y[idx]

In [ ]:
train_dataset=customDataset(x_train_tensor,y_train_tensor)
test_dataset=customDataset(x_test_tensor,y_test_tensor)

In [ ]:
# DATALOADER CLASS
train_loader=torch.utils.data.DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader=torch.utils.data.DataLoader(test_dataset,batch_size=32,shuffle=False)

##model

In [ ]:
class MyModel():
  def __init__(self,x):

    self.w=torch.randn(x.shape[1],1,requires_grad=True)   #initialising weights equal to no.of cols in x
    self.b=torch.randn(1,requires_grad=True)              #initialising bias equal to no.of neurons

  def forward(self,x):
    z=torch.matmul(x,self.w)+self.b
    y_hat=torch.sigmoid(z)
    return y_hat

  def loss(self,y_hat,y):
    y=y.unsqueeze(1)
    loss=torch.nn.functional.binary_cross_entropy(y_hat,y)
    return loss

  def train(self,train_loader,epochs=25,lr=0.01):

    for epoch in range(epochs):                #for each epoch

      for batch_x, batch_y in train_loader:    # for every batch

        #forward
        y_hat=self.forward(x)

        #loss
        loss=self.loss(y_hat,y)
        print("epoch:",epoch,"loss:",loss.item())

        #backward
        loss.backward()

        #parameter update
        with torch.no_grad():           # not storing history or gradients
          self.w-=lr*self.w.grad
          self.b-=lr*self.b.grad

        #zeroing gradients
        self.w.grad.zero_()
        self.b.grad.zero_()

  def predict(self,test_loader):
    with torch.no_grad():
      for batch_x, batch_y in test_loader:       #for every batch
        y_pred=self.forward(x)
        y_pred=torch.where(y_pred>0.5,1,0)
    return y_pred


In [ ]:
#creaing instance
model=MyModel(x_train_tensor)

In [ ]:
#train
model.train(train_loader)

TypeError: matmul(): argument 'input' (position 1) must be Tensor, not DataFrame

In [ ]:
#predict
y_pred=model.predict(x_test_tensor)

#accuracy
accuracy=torch.mean((y_pred.float()==y_test_tensor.float()).float())
print("accuracy:",accuracy)

accuracy: tensor(0.5194)


In [ ]:
##Evaluation

model.eval()
accuracy=[]

with torch.no_grad():
  for batch_x, batch_y in test_loader:
    y_pred=model(x_test_tensor)
    y_pred=torch.where(y_pred>0.5,1,0)
    #accuracy
    batch_accuracy=torch.mean((y_pred.float()==y_test_tensor.float()).float())
    print("Batch accuracy:",accuracy)

    accuracy.append(batch_accuracy.item())

print("Average accuracy:",np.mean(accuracy))